### ISSUE TITLE
Review required properties in schema

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/rac-data-model#23]
Review and possibly change or extend required properties. Some of the initial choices were a bit subjective. I tried to think through some different iterations of data we might have, but should definitely scrutinize more.

**Comment by helrond** [comment]
It may be useful to think about this also from the perspective of what data elements are useful in the front end. For example, I set the `begin` property of dates as required, even though I know that means we'll have to parse expressions and do some inheriting (and maybe more), because having that structure data will allow us to do a lot more in terms of faceting and other structured searching in the discovery interface.

There's definitely a push/pull between the effort it will take to ensure certain data elements are always present versus the benefit of that certainty, but I want to make sure we consider both of those things in combination!
